log_level: "Info"
parallel: 4
runner:
  target_rps: 8000
  duration: "30s"
  batch_size: "Auto"
  # batch_size: 2
  # auto_throttle: true
  base_url: "http://localhost:8080"
  global:
    variables:
      - name: COUNTER
        function:
          type: Incremental
          start: 0
          threshold: 100000
          steps: 1
      - name: RANDOM
        function:
          type: Random
          min: 0
          max: 100000
  # delay_between_scenario: "500ms"
  scenarios:
    - name: createSubscriber
      request:
        method: POST
        path: "/rsgateway/data/json/subscriber"
        body: |
          {
            "$": "MtxRequestSubscriberCreate",
            "Name": "James Bond",
            "FirstName": "James_${COUNTER}_${RANDOM}",
            "LastName": "Bond",
            "ContactEmail": "james.bond@email.com"
          }
      response:
        assert:
          status: 200
        define:
          - name: ExternalId
            from: $.ObjectId
    - name: querySubscriber
      request:
        method: GET
        path: "/rsgateway/data/json/subscriber/query/ExternalId/${ExternalId}"
      response:
        assert:
          status: 200
