log_level: "Trace"
parallel: 1
runner:
  target_rps: 3
  duration: 2s
  batch_size: "Auto"
  # batch_size: 2
  base_url: "http://localhost:8081"
  global:
    variables:
        # run: |
        #   let COUNTER = 0
        #   let IMSI = 11000
      - name: COUNTER
        value: 0
      - name: IMSI
        value: 110000
  scenarios:
    - name: chargingDataCreate
      pre-script:
        # run: |
        #   let now = Now()
        #   let random = Random()
        #   let IMSI = IMSI + 1
        #   let imsi = IMSI
        variables:
          - name: now
            function:
              type: Now 
          - name: random
            function:
              type: Random
              min: 100
              max: 999
          - name: IMSI
            function:
              type: Plus
            args:
              - $IMSI
              - 1
          - name: imsi
            function:
              type: Copy
            args:
              - $IMSI
      request:
        method: POST
        path: "/nchf-convergedcharging/v2/chargingdata"
        headers: 
        - content-type: "application/json"
        body: |
          {
            "notifyUri": "http://chf/callback/notify",
            "oneTimeEvent": true,
            "invocationSequenceNumber": ${COUNTER},
            "invocationTimeStamp": "${now}",
            "subscriberIdentifier": "imsi-${imsi}",
            "nfConsumerIdentification": {
              "nFIPv6Address": "2001:db8:85a3::8a2e:370:7334",
              "nFIPv4Address": "198.51.100.1",
              "nFName": "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
              "nodeFunctionality": "SMF",
              "nFPLMNID": {
                "mnc": "${random}",
                "mcc": "${random}"
              }
            }
          }
        timeout: 3s
      response:
        assert:
          status: 201
          headers: 
          - name: "location"
            value:
              type: "NotNull"
          - name: "content-type"
            value:
              type: "Equal"
              value: "application/json"
          body:
          - name: "invocationSequenceNumber"
            value:
              type: "NotNull"
        define:
          - name: location
            from: Header
            path: "location"
      post-script:
        # run: |
        #   let COUNTER = COUNTER + 1
        #   let chargingDataRef = location.split("/", Last)
        variables:
          - name: COUNTER
            function:
              type: Plus
            args:
              - $COUNTER
              - 1
          - name: chargingDataRef
            function:
              type: Split
              delimiter: "/"
              index:
                type: Last
            args:
              - $location

    - name: chargingDataUpdate
      request:
        method: POST
        path: "/nchf-convergedcharging/v2/chargingdata/${chargingDataRef}/update"
        headers: 
        - content-type: "application/json"
        body: |
          {
            "invocationSequenceNumber": ${COUNTER},
            "invocationTimeStamp": "${now}",
            "subscriberIdentifier": "imsi-${imsi}",
            "nfConsumerIdentification": {
              "nFIPv6Address": "2001:db8:85a3::8a2e:370:7334",
              "nFIPv4Address": "198.51.100.1",
              "nFName": "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
              "nodeFunctionality": "SMF",
              "nFPLMNID": {
                "mnc": "${random}",
                "mcc": "${random}"
              }
            }
          }
        timeout: 3s
      response:
        assert:
          status: 200
      post-script:
        # run: |
        #   let COUNTER = COUNTER + 1
        variables:
          - name: COUNTER
            function:
              type: Plus
            args:
              - $COUNTER
              - 1
    - name: chargingDataRelease
      request:
        method: POST
        path: "/nchf-convergedcharging/v2/chargingdata/${chargingDataRef}/release"
        headers: 
        - content-type: "application/json"
        body: |
          {
            "invocationSequenceNumber": ${COUNTER},
            "invocationTimeStamp": "${now}",
            "subscriberIdentifier": "imsi-${imsi}",
            "nfConsumerIdentification": {
              "nFIPv6Address": "2001:db8:85a3::8a2e:370:7334",
              "nFIPv4Address": "198.51.100.1",
              "nFName": "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
              "nodeFunctionality": "SMF",
              "nFPLMNID": {
                "mnc": "${random}",
                "mcc": "${random}"
              }
            }
          }
        timeout: 3s
      response:
        assert:
          status: 204
      post-script:
        # run: |
        #   let COUNTER = COUNTER + 1
        variables:
          - name: COUNTER
            function:
              type: Plus
            args:
              - $COUNTER
              - 1
