log_level: "Info"
parallel: 1
runner:
  target_rps: 1
  duration: "5s"
  batch_size: "Auto"
  # auto_throttle: true
  base_url: "http://localhost:8080"
  variables:
    - name: COUNTER
      properties:
        type: Incremental
        min: 0
        max: 100000
        steps: 1
    - name: RANDOM
      properties:
        type: Random
        min: 0
        max: 100000
  # delay_between_scenario: "500ms"
  scenarios:
    - name: createSubscriber
      request:
        method: POST
        path: "/rsgateway/data/json/subscriber"
        body: |
          {
            "$": "MtxRequestSubscriberCreate",
            "Name": "James Bond",
            "FirstName": "James_${COUNTER}_${RANDOM}",
            "LastName": "Bond",
            "ContactEmail": "james.bond@email.com"
          }
      response:
        status: 200
    # - name: querySubscriber
    #   method: GET
    #   path: "/rsgateway/data/json/subscriber/query/ExternalId/:externalId"
